### ISSUE TITLE
Enable storing score history

### ISSUE THREAD

**Issue by n-ce** [n-ce/Arithmetic-Speed-Drill#2]
Have another html page showing previous scores with date and time.
The scores must be saved using cookies.
New scores should be saved when there is no time left.

**Comment by ar1hant** [comment]
Added the cookies feature.
Want to check it out?
https://ar1hant.github.io/Arithmetic_speed_drill/

**Comment by n-ce** [comment]
I checked my cookies, 1 is available that must be it, also you need to create a history button to access those cookies (beside restart is fine) which onclick will give us the list.
